import Header from "@/_templates/header/header";
import type { Metadata } from "next";
import "./global.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import 
{
  AkzidenzGroteskBoldExtended,
  AkzidenzGroteskMediumExtended,
  RidleyGroteskBold,
  RidleyGroteskMedium,
  RidleyGroteskRegular,
  RubikLight,
  RubikMedium,
  RubikRegular
} from "@/lib/fonts"

export const metadata: Metadata = {
  title: "Erkin hereket",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages()
  return (
    <NextIntlClientProvider messages={messages}>
    <html lang="en">
      <body className={`
        ${AkzidenzGroteskBoldExtended.className} 
        ${AkzidenzGroteskMediumExtended.className} 
        ${RidleyGroteskBold.className} 
        ${RidleyGroteskMedium.className} 
        ${RidleyGroteskRegular.className} 
        ${RubikLight.className} 
        ${RubikMedium.className} 
        ${RubikRegular.className} 
        `}>
          <Header />
          {children}
      </body>
    </html> 
    </NextIntlClientProvider>
  );
}