import Header from "@/_templates/header/header";
import type { Metadata } from "next";
import "./global.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import {
AkzidenzGroteskBoldExtended,
AkzidenzGroteskMediumExtended,
RidleyGroteskBold,
RidleyGroteskMedium,
RidleyGroteskRegular,
RubikLight,
RubikMedium,
RubikRegular
} from "@/lib/fonts"

export const metadata: Metadata = {
  title: "Erkin hereket",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode,
  params: { locale: string };
}>) {
  const messages = await getMessages({ locale })
  return (
    <html lang={locale}>
      <body className={`
        ${AkzidenzGroteskBoldExtended.className} 
        ${AkzidenzGroteskMediumExtended.className} 
        ${RidleyGroteskBold.className} 
        ${RidleyGroteskMedium.className} 
        ${RidleyGroteskRegular.className} 
        ${RubikLight.className} 
        ${RubikMedium.className} 
        ${RubikRegular.className} 
        `}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}